site_name: Leitfaden Test

site_url:  http://egov-leitfaden.readthedocs.io/
site_author: Ina Stein
site_description:
# Repository
#repo_name:
#repo_url:
#edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 eGov-Campus

# Configuration

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

docs_dir: docs
theme:
  name: material
  language: de
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - header.autohide
  font:
    text: Encode Sans
  palette:
   - scheme: eGov




nav:
  - Home: 'index.md'
  - Kursdesign:
    - Kurse konzipieren: 'kursdesign/kursdesign.md'
  - LMS:
    - Einführung ins LMS: 'lms/lms.md'
  - Über den eGov-Campus: 'about.md'
